#! /bin/bash

# --------------------------------------------------
# Project monitor:
#       https://github.com/Statemood/monitor
#
# Created by Statemood, 2016-11-07
#
# --------------------------------------------------

case "$1" in
    status)
        sestatus | grep '^SELinux status' | awk -F ':' '{print $2}' | awk '{print $1}'
        ;;
    current)
        mode=`sestatus | grep '^Current mode' | awk '{print $3}'`
        test -z "$mode" && mode=disabled
        echo $mode
        ;;
    config)
        grep '^SELINUX=' /etc/selinux/config | awk -F '=' '{print $2}'
        ;;
esac