#! /bin/sh

# ------------------------------------------
# Project Monitor
#       https://github.com/Statemood/monitor
#
# Lin Ru Lin.Ru@msn.com
# ------------------------------------------

 id="$1"
arg="$2"

get(){
    sudo docker stats --no-stream $1 | tail -1
}

raw(){
    if grep -q "GiB" <<< $1
    then
        n=`echo $1 | sed 's/GiB//'`
        echo "$n * 1024 * 1024 * 1024" | bc
        exit
    fi

    if grep -q "MiB" <<< $1
    then
        n=`echo $1 | sed 's/MiB//'`
        echo "$n * 1024 * 1024" | bc
        exit
    fi

    if grep -q "KiB" <<< $1
    then
        n=`echo $1 | sed 's/KiB//'`
        echo "$n * 1024" | bc
        exit
    fi

    if grep -q "B" <<< $1
    then
        echo $1 | sed 's/B//'
        exit
    fi
}

case $arg in
    --name)              get $id | awk '{print $2}'                 ;;
    --cpu)               get $id | awk '{print $3}' | sed 's/%//'   ;;
    --mem_percent)       get $id | awk '{print $7}' | sed 's/%//'   ;;
    --mem_usage)    raw `get $id | awk '{print $4}'`                ;;
    --mem_limit)    raw `get $id | awk '{print $6}'`                ;;
    --net_i)        raw `get $id | awk '{print $8}'`                ;;
    --net_o)        raw `get $id | awk '{print $10}'`               ;; 
    --block_i)      raw `get $id | awk '{print $11}'`               ;; 
    --block_o)      raw `get $id | awk '{print $13}'`               ;;
esac