#!/usr/bin/env python
#coding=utf-8

import os
import json

t       = os.popen("grep '[hsv]d[a-z]' /proc/diskstats | awk '{print $3}'")

disks = []
for disk in  t.readlines():
        r = os.path.basename(disk.strip())
        disks += [{'{#DISKDEV}':r}]
print json.dumps({'data':disks},sort_keys=True,indent=4,separators=(',',':'))
