#! /bin/bash

# ------------------------------------------
# Project Monitor
#       https://github.com/Statemood/monitor
#
# Lin Ru Lin.Ru@msn.com
# ------------------------------------------

 id="$1"
arg="$2"
if [ "$1" == "" ]; then
	exit 1
fi

KB=1024
MB=$(($KB * 1024))
GB=$(($MB * 1024))
stats=($(sudo docker stats --no-stream $1 | tail -1))

raw() {
	cnt=$(echo $1 | tr -cd "[0-9.]")
	case $1 in
		*"GiB")	echo "$cnt * $GB" | bc	;;
		*"MiB")	echo "$cnt * $MB" | bc	;;
		*"KiB")	echo "$cnt * $KB" | bc	;;
		*"kB")	echo "$cnt * $KB" | bc	;;
		*"B")	echo $cnt		;;
		*"%")	echo $1 | tr -d '%'	;;
		*)	echo $1			;;
	esac
}

case $arg in
	--name)		echo "${stats[1]}"	;;
	--cpu)		raw "${stats[2]}"	;;
	--mem_percent)	raw "${stats[6]}"	;;
	--mem_usage)	raw "${stats[3]}"	;;
	--mem_limit)	raw "${stats[5]}"	;;
	--net_i)	raw "${stats[7]}"	;;
	--net_o)	raw "${stats[9]}"	;;
	--block_i)	raw "${stats[10]}"	;;
	--block_o)	raw "${stats[12]}"	;;
esac
