#! /bin/bash

# ------------------------------------------
#
#       https://github.com/Statemood/monitor
# ------------------------------------------

GetInfo(){
    sudo /opt/megaraid/megacli -AdpAllInfo -a${adapter} -NoLog
}

DCIF(){
    GetInfo | grep -A 5 '^Physical Devices' | grep -A 5 'Supported Adapter Operations'
}

# RAID INFO: filter
RIF(){
    GetInfo | grep "^$key" | awk -F ': ' '{print $2}'
}

for args in "$@"
do 
    case $args in
        --adapter)
            adapter="$2"
            shift 2
            ;;
        --item)
            case "$2" in
                disk_critical)
                        DCIF | grep 'Critical'   | awk -F ': ' '{print $2}'
                        exit
                        ;;
                disk_failed)
                        DCIF | grep 'Failed'     | awk -F ': ' '{print $2}'
                        exit
                        ;;
                disk_total)
                        DCIF | grep 'Physical Devices' | awk -F ': ' '{print $2}'
                        exit
                        ;;
                pn)     key="Product Name"                  ;;
                sn)     key="Serial No"                     ;;
                nbp)    key="Number of Backend Port"        ;;
                mem)    key="Memory Size"
                        RIF | tr -s "A-Z" " "
                        exit 0
                        ;;
                mce)    key="Memory Correctable Errors"     ;;
                mue)    key="Memory Uncorrectable Errors"   ;;
                mfd)    key="Mfg. Date"                     ;;
                bbu)    key="BBU"                           
                        RIF | egrep -i 'Absent|Present'
                        exit 0
                        ;;
                rt)     key="ROC temperature"
                        res=`RIF | awk '{print $1}'`

                        test -z "$res" && echo 0 || echo $res
                        exit 0
                        ;;
                tc)     key="Controller temperature"
                        res=`RIF | awk '{print $1}'`

                        test -z "$res" && echo 0 || echo $res
                        exit 0
                        ;;
                ct)     key="Current Time"
                        RIF | awk '{print $3"-"$2,$1}' | tr "/" "-" | sed 's/,//'
                        exit 0
                        ;;
                level)
                        
            esac
        shift 2
        ;;
    esac
done 

RIF