#! /bin/bash

# ------------------------------------------
# Project Monitor
#       https://github.com/Statemood/monitor
#
# Lin Ru Lin.Ru@msn.com
# ------------------------------------------

osd_stats        (){ ceph osd stat                  |  awk "{print \$$1}"    ; }
osd_pools        (){ ceph status   | grep 'pools: ' |  awk "{print \$$1}"    ; }
osd_usage_data   (){ ceph -s | grep 'usage:' | awk -F "$1" "{print \$$2}"    ; }
osd_usage_used   (){ osd_usage_data , 1 |         awk -F ':' '{print $2}'    ; }
osd_usage_avail  (){ osd_usage_data / 1 |         awk -F ',' '{print $2}'    ; }
osd_usage_total  (){ osd_usage_data / 2                                      ; }
osd_usage_objects(){ ceph -s | grep 'objects' | awk "{print \$$1}"       ; }
osd_usage_objsize(){ osd_usage_objects '4,$5'                    ; }

osd_usage(){
    s="`$1 | awk '{print $2}'`"
    n="`$1 | awk '{print $1}'`"

    case $s in
        MB)     echo "$(($n * 1024 * 1024))"                 ;;
        GB)     echo "$(($n * 1024 * 1024 * 1024))"          ;;
        TB)     echo "$(($n * 1024 * 1024 * 1024 * 1024))"   ;;
    esac
}
ceph_health(){
    hs="`ceph -s | grep 'health:' | awk -F ': ' '{print $2}'`"

    case $hs in
        HEALTH_OK)      echo 0  ;;
        HEALTH_WARN)    echo 1  ;;
        HEALTH_ERR)     echo 2  ;;
    esac
}
io_client(){
    # $1,  1 = Read  bps   2 = Write bps   3 = Read  IOPS  4 = Write IOPS
    ceph -s | grep -A 1 "io:" | tail -1 | awk -F ':' '{print $2}' | awk  -F ',' "{print \$$1}"
}

io_msg(){
    n=` io_client $1 | awk '{print $1}'`
    s="`io_client $1 | awk '{print $2}' | awk -F '/' '{print $1}'`"

    case $s in
        op|B)     res="$n"                     		;;
          kB)     res=`echo "$(($n * 1024))"`  		;;
          mB)     res=`echo "$(($n * 1024 * 1024))"`	;;
    esac

    test -z "$res" && echo 0 || echo $res
}

obj_number(){
    obj_str="`osd_usage_objects 2`"
    obj_num=`echo $obj_str | awk -F '[kmg]' '{print $1}'`

    echo "$(($obj_num * 1000))"
}

case $1 in
    osd_total)  osd_stats   1   ;;
       osd_up)  osd_stats   3   ;;
       osd_in)  osd_stats   5   ;;
        pools)  osd_pools   2   ;;
          pgs)  osd_pools   4   ;;
         io_r)  io_msg      1   ;;  # Read  B/s
         io_w)  io_msg      2   ;;  # Write B/s
        ops_r)  io_msg      3   ;;  # OPS Read  per sec
        ops_w)  io_msg      4   ;;  # OPS Write per sec
       health)  ceph_health     ;;
         used)  osd_usage osd_usage_used      ;;
        avail)  osd_usage osd_usage_avail     ;;
        total)  osd_usage osd_usage_total     ;;
      obj_num)  obj_number                    ;;
     obj_size)  osd_usage osd_usage_objsize   ;;
esac
