#!/usr/bin/env python
#coding=utf-8

import os
import json

t  = os.popen("""sudo /opt/megaraid/megacli -AdpAllInfo -aALL -NoLog |\
                 grep '^Adapter ' | awk -F '#' '{print $2}'          |\
                 while read id; do sudo /opt/megaraid/megacli -AdpBbuCmd -GetBbuStatus -a$id -NoLog |\
                     grep -q '^BBU status for Adapter'; test $? = 0 && echo $id; done
             """)

items = []
for item in  t.readlines():
        r = os.path.basename(item.strip())
        items += [{'{#BBU.ADAPTER}':r}]
print json.dumps({'data':items},sort_keys=True,indent=4,separators=(',',':'))