#! /bin/bash

# ------------------------------------------
#
#       https://github.com/Statemood/monitor
# ------------------------------------------

# chss --host a --port b --url c
port="80"
host="localhost"
opts="--max-time 5 --retry 3 --retry-delay 1"
 url="/server-status"

Status(){
    curl ${opts} ${host}:${port}${url}
}

for arg in "$@"
do
    case $arg in
        version)

          built_time)
        current_time)
        restart_time)
              uptime)
        being_processed)
        idle_workers)
        waiting)
        starting)
        reading)
        sending)
        keepalive)
        dns_lookup)
        closing)
        logging)
        finishing)

    esac
done
