#! /bin/bash

# ------------------------------------------
#
#       https://github.com/Statemood/monitor
# ------------------------------------------

# line of the disk info filtered by '^Solt Number: X'
di_line=45

megacli=/usr/local/bin/megacli

disk_info=/dev/shm/disk.info
raid_info=/dev/shm/raid.info

# Refresh data
refresh(){
    case $1 in
        disk)   sudo $megacli -PDList     –a0 -NoLog > $disk_info   ;;
        raid)   sudo $megacli -adpallinfo -a0 -NoLog > $raid_info   ;;
    esac
}

# DISK COUNT INFO: filter
DCIF(){
    grep -A 5 '^Physical Devices' $raid_info
}

# DISK COUNT INFO: output
DCIO(){
    case $1 in
        critical)   DCIF | grep 'Critical'   | awk '{print $3}'     ;;
        failed)     DCIF | grep 'Failed'     | awk '{print $3}'     ;;
        total)      DCIF | head -2 | tail -1 | awk '{print $3}'     ;;
    esac
}

# RAID INFO: filter
RIF(){
    grep "^$key" $raid_info | awk -F ': ' '{print $2}'
}

# RAID INFO: output
RIO(){
    case $1 in
        PN)     key="Product Name"           ;;
        SN)     key="Serial No"              ;;
        NBP)    key="Number of Backend Port" ;;
        MEMORY) key="Memory Size"
                RIF | tr -s "A-Z" " "
                exit 0
                ;;
        MCE)    key="Memory Correctable Errors"     ;;
        MUE)    key="Memory Uncorrectable Errors"   ;;
        TR)     key="ROC temperature"
                RIF | awk '{print $1}'
                exit 0
                ;;
        TC)     key="Controller temperature"
                RIF | awk '{print $1}'
                exit 0
                ;;
        CT)     key="Current Time"
                RIF | awk '{print $3"-"$2,$1}' | tr "/" "-" | sed 's/,//'
                exit 0
                ;;
    esac
    RIF
}
