#! /bin/sh

# ------------------------------------------
# Project Monitor
#       https://github.com/Statemood/monitor
#
# Lin Ru Lin.Ru@msn.com
# ------------------------------------------

 id="$1"
arg="$2"


case $args in
    --name)
    --ip)
    --mac)
    --status)
    --oom)
    --started)
    --error)
    --driver)
    --restartpolicy)
    --privileged)
    --cpu)
    --memory)
    --disk)
    --ulimits)
esac