#! /bin/bash

# ------------------------------------------
#
#       https://github.com/Statemood/monitor
# ------------------------------------------

gen_data(){
    for cpu in `grep '^physical id' /proc/cpuinfo | sort | uniq | awk -F ': ' '{print $2}'`
    do
        for core in `sensors -A | sed -e '/./{H;$!d;}' -e "x;/coretemp-isa-000$cpu/b" -e d | grep '^Core [0-9].' | awk -F ':' '{print $1}' | awk '{print $2}'`
        do
            echo "${cpu}_${core}"
        done
    done
}
data=(`gen_data`)

len=${#data[@]}

printf "{\n"
printf  '\t'"\"data\":["
for ((i=0;i<$len;i++))
do
        printf '\n\t\t{'
        printf "\"{#PCOREID}\":\"${data[$i]}\"}"
        if [ $i -lt $[$len-1] ]
        then
            printf ','
        fi
done

printf  "\n\t]\n"
printf "}\n"