#! /bin/bash

# ------------------------------------------
#
#       https://github.com/Statemood/monitor
# ------------------------------------------

argv="$1"

temp_data(){
    sensors | grep "^Physical id $cpu:" | awk -F '+' '{print $2}' | awk -F '.' '{print $1}'
}

case "$argv" in
    temp*)
        #temp0, temp1
        cpu="`echo $argv | cut -c 5`"
        temp_data
        ;;
esac
