#! /bin/bash

# --------------------------------------------------
# Project monitor:
#       https://github.com/Statemood/monitor
#
#
# --------------------------------------------------
# service:abc.com:192.168.1.100:8080:302:/api
#
# host=xyz.com, ip=use dns, port=default is 80, http_code=default is 200, uri=default is '/'
# :xyz.com:::::
#
# host=default use ip, ip=192.168.1.20,21,22,23, port=default, http_code=default, uri=/api
# ::192.168.1.20-23:::/api

   tag=1
 count=1
number=1
  temp=`mktemp /dev/shm/XXXXXXXXXXXX`
config="$(dirname $(dirname $0))/etc/http-discovery.list"

$(dirname $0)/generate_http_discovery_list

if [ ! -f "$config" ]
then
    echo "Error: config file not found"
    exit 1
fi

dl_process(){
    # 192.168.1.10
    ip_full="`echo $ip  | awk -F '-' '{print $1}'`"
    # get 192.168.1 of 192.168.1.10-xxx
    ip_head="`echo $ip_full | awk -F '.' '{print $1,$2,$3}' | sed 's/ /./g'`"
    # transfer 10-20 to 10 and 20
    ip_range0="`echo $ip | awk -F '.' '{print $3}'`"
    ip_range1="`echo $ip | awk -F '.' '{print $4}' | awk -F '-' '{print $1}'`"
    ip_range2="`echo $ip | awk -F '.' '{print $4}' | awk -F '-' '{print $2}'`"

    for ((i=$ip_range1; i<=$ip_range2; i++))
    do
        n=1
        if [ $tag = 0 ]
        then
            host="$ip_head.$i"
        else
            test "$host" = "0" && host="$ip_head.$i" && n=0
        fi

        # get 1-10 of 192.168.1.10
        #server=`echo $ip_full | awk -F '.' '{print $3,$4}' | tr " " "-"`
         server="$ip_range0-$i"
        items_0="{\"{#HTTP.SERVICE}\": \"$service\", \"{#HTTP.SERVER}\": \"$server\","
        items_1="{#HTTP.HOST}\": \"$host\", \"{#HTTP.IP}\": \"$ip_head.$i\","
        items_2="{#HTTP.PORT}\": $port, \"{#HTTP.CODE}\": $code, \"{#HTTP.URI}\": \"$uri\","
        items_3="{#HTTP.ID}\": \"$id\"}"

        echo "$items_0$items_1$items_2$items_3"    >> $temp

        test $n = 0 && host=0
    done
}

grep -v "^#" $config | sed '/^$/d' |\
while read line
do
    service="`echo $line | awk -F ':' '{print $1}'`"
       host="`echo $line | awk -F ':' '{print $2}'`"
         ip="`echo $line | awk -F ':' '{print $3}'`"
       port="`echo $line | awk -F ':' '{print $4}'`"
       code="`echo $line | awk -F ':' '{print $5}'`"
        uri="`echo $line | awk -F ':' '{print $6}'`"
         id="`echo $line | awk -F ':' '{print $7}'`"

echo s=$service, h=$host, ip=$ip, c=$code, p=$port, u=$uri, id=$id
    test -z "$host" && host=0
    test -z "$ip"   &&   ip=0   && tag=0
    test -z "$port" && port=80
    test -z "$code" && code=200
    test -z "$uri"  &&  uri="/"
    echo s=$service, h=$host, ip=$ip, c=$code, p=$port, u=$uri, id=$id
    test "$ip" = "$host" && test "$ip" = 0 && continue

    # for 192.168.1.10-20, 22-25
    test $ip = 0 && ip="$host"
    echo "$ip" | grep "\-" | grep -q ","
    if [ $? = 0 ]
    then
         ip_old="$ip"
        ip_head="`echo $ip_full | awk -F '.' '{print $1,$2,$3}' | sed 's/ /./g'`"
        for ipa in `echo $ip | awk -F '.' '{print $4}' | sed 's/,/ /g'`
        do
            for ip in $ip_head.$ipa
            do
                dl_process
            done
        done

        continue
    fi

    # for 192.168.1.10-20
    echo "$ip" | grep -q "\-"
    if [ $? = 0 ]
    then
        dl_process
    fi
done

printf  '{\n\t'"\"data\":["

total=`wc -l $temp | awk '{print $1}'`
while read line
do
    if [ $count = $total ]
    then
        echo "$line"
        #echo "{\"{#TOTAL.ITEMS}\": $total}"
    else
        echo "$line,"
        echo $((count++)) > /dev/null
    fi
done < $temp

printf  "\n\t]\n}\n"

test -f "$temp" && rm -rf "$temp"
