#! /bin/bash

# ------------------------------------------
# 
# Created by Statemood, 2013.08.11 19:50
# Updated by Statemood, 2013.09.28 10.35
#            Statemood@gmail.com
#
# Project mgutils:
#    https://github.com/Statemood/nagios-plugs
# ------------------------------------------


